apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    dedicated: webapp
spec:
  nodeSelector:
    kubernetes.io/hostname: worker1
  containers:
  - name: webapp
    image: rusita/app:v1
    ports:
    - containerPort: 8080
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "webapp"
    effect: "NoSchedule"

