apiVersion: v1
kind: Pod 
metadata:
  name: annotation-nodejs
  labels:
    app: nodejs
  annotations:
    manufacturer: "cloud"
    e-mail: "cloud@example.com"
    release-version: "v1"
spec:
  containers:
  - name: nodejs
    image: rusita/app:v1
    ports:
    - containerPort: 80

