apiVersion: v1
kind: Pod
metadata:
  name: label-app01
  labels:
    app: nodejs
    environment: develop
    release: beta
spec:
  containers:
    - name: nodejs
      image: rusita/app:v1
      ports:
      - containerPort: 80

