apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-canary-svc
  name: blue-canary-svc
  namespace: default
spec:
  ports:
  - nodePort: 30880
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: webapp
  type: NodePort

