apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-canary
  labels:
    app: webapp
    release: beta
  annotations:
    kubernetes.io/change-cause: release beta
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: webapp
      release: beta
  template:
    metadata:
      labels:
        app: webapp
        release: beta
    spec:
      containers:
      - name: deploy-canary
        image: rusita/web:canary
        ports:
        - containerPort: 80

