apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-hostname-service
spec:
  type: LoadBalancer
  selector:
    app: hostname-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

