apiVersion: v1
kind: Service
metadata:
  name: nfs-service
spec:
  type: ClusterIP
  clusterIP: 10.96.174.73
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    role: nfs-server

