apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx-label
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values: 
      - web
      - nginx
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx
        ports:
        - containerPort: 80
  replicas: 3

