apiVersion: v1
kind: Pod
metadata:
  name: configmap-envfrom-demo
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      envFrom:
        - configMapRef:
            name: configmap-game
        - configMapRef:
            name: configmap-ui

