apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-demo
spec:
  containers:
    - name: volume-demo
      image: alpine
      command: ["sleep", "3600"]
      volumeMounts:
      - name: config
        mountPath: /config
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: configmap-game-env

