apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green-svc
  name: blue-green-svc
  namespace: default
spec:
  ports:
  - nodePort: 30880
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-blue
  type: NodePort

