apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-green
  labels:
    app: deploy-green
    release: stable
  annotations:
    kubernetes.io/change-cause: release green 
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: deploy-green
      release: stable
  template:
    metadata:
      labels:
        app: deploy-green
        release: stable
    spec:
      containers:
      - name: deploy-green
        image: rusita/web:green
        ports:
        - containerPort: 80

